[project]
name = "rascal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch==2.5.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
